{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-7886", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "cloudme", "product": {"product_data": [{"product_name": "sync", "version": {"version_data": [{"version_value": "1.10.9", "version_affected": "<="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-119"}]}]}, "references": {"reference_data": [{"url": "https://0day4u.wordpress.com/2018/03/09/buffer-overflow-on-cloudme-sync-v1-11-0/", "name": "https://0day4u.wordpress.com/2018/03/09/buffer-overflow-on-cloudme-sync-v1-11-0/", "refsource": "MISC", "tags": ["Exploit", "Third Party Advisory"]}, {"url": "https://www.exploit-db.com/exploits/44470/", "name": "44470", "refsource": "EXPLOIT-DB", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "An issue was discovered in CloudMe 1.11.0. An unauthenticated local attacker that can connect to the 'CloudMe Sync' client application listening on 127.0.0.1 port 8888 can send a malicious payload causing a buffer overflow condition. This will result in code execution, as demonstrated by a TCP reverse shell, or a crash. NOTE: this vulnerability exists because of an incomplete fix for CVE-2018-6892."}]}}
