{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-9145", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "exiv2", "product": {"product_data": [{"product_name": "exiv2", "version": {"version_data": [{"version_value": "0.26", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-20"}]}]}, "references": {"reference_data": [{"url": "https://bugzilla.novell.com/show_bug.cgi?id=1087879", "name": "https://bugzilla.novell.com/show_bug.cgi?id=1087879", "refsource": "MISC", "tags": []}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1564281", "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1564281", "refsource": "MISC", "tags": []}, {"url": "https://github.com/xiaoqx/pocs/tree/master/exiv2", "name": "https://github.com/xiaoqx/pocs/tree/master/exiv2", "refsource": "MISC", "tags": ["Exploit", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "In the DataBuf class in include/exiv2/types.hpp in Exiv2 0.26, an issue exists in the constructor with an initial buffer size. A large size value may lead to a SIGABRT during an attempt at memory allocation. NOTE: some third parties have been unable to reproduce the SIGABRT when using the 4-DataBuf-abort-1 PoC file."}]}}
