{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-1000117", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "python", "product": {"product_data": [{"product_name": "python", "version": {"version_data": [{"version_value": "3.2.0", "version_affected": "="}, {"version_value": "3.2.1", "version_affected": "="}, {"version_value": "3.2.2", "version_affected": "="}, {"version_value": "3.2.3", "version_affected": "="}, {"version_value": "3.2.4", "version_affected": "="}, {"version_value": "3.2.5", "version_affected": "="}, {"version_value": "3.2.6", "version_affected": "="}, {"version_value": "3.2.2150", "version_affected": "="}, {"version_value": "3.3", "version_affected": "="}, {"version_value": "3.3.0", "version_affected": "="}, {"version_value": "3.3.1", "version_affected": "="}, {"version_value": "3.3.2", "version_affected": "="}, {"version_value": "3.3.3", "version_affected": "="}, {"version_value": "3.3.4", "version_affected": "="}, {"version_value": "3.3.5", "version_affected": "="}, {"version_value": "3.3.6", "version_affected": "="}, {"version_value": "3.3.7", "version_affected": "="}, {"version_value": "3.4", "version_affected": "="}, {"version_value": "3.4.0", "version_affected": "="}, {"version_value": "3.4.1", "version_affected": "="}, {"version_value": "3.4.2", "version_affected": "="}, {"version_value": "3.4.3", "version_affected": "="}, {"version_value": "3.4.4", "version_affected": "="}, {"version_value": "3.4.5", "version_affected": "="}, {"version_value": "3.4.6", "version_affected": "="}, {"version_value": "3.4.7", "version_affected": "="}, {"version_value": "3.5", "version_affected": "="}, {"version_value": "3.5.0", "version_affected": "="}, {"version_value": "3.5.1", "version_affected": "="}, {"version_value": "3.5.2", "version_affected": "="}, {"version_value": "3.5.3", "version_affected": "="}, {"version_value": "3.5.4", "version_affected": "="}, {"version_value": "3.5.5", "version_affected": "="}, {"version_value": "3.5.6", "version_affected": "="}, {"version_value": "3.6", "version_affected": "="}, {"version_value": "3.6.0", "version_affected": "="}, {"version_value": "3.6.1", "version_affected": "="}, {"version_value": "3.6.2", "version_affected": "="}, {"version_value": "3.6.3", "version_affected": "="}, {"version_value": "3.6.4", "version_affected": "="}, {"version_value": "3.7", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-119"}]}]}, "references": {"reference_data": [{"url": "https://bugs.python.org/issue33001", "name": "https://bugs.python.org/issue33001", "refsource": "CONFIRM", "tags": ["Issue Tracking", "Patch", "Third Party Advisory"]}, {"url": "https://github.com/python/cpython/pull/5989", "name": "https://github.com/python/cpython/pull/5989", "refsource": "CONFIRM", "tags": ["Issue Tracking", "Patch", "Vendor Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "Python Software Foundation CPython version From 3.2 until 3.6.4 on Windows contains a Buffer Overflow vulnerability in os.symlink() function on Windows that can result in Arbitrary code execution, likely escalation of privilege. This attack appears to be exploitable via a python script that creates a symlink with an attacker controlled name or location. This vulnerability appears to have been fixed in 3.7.0 and 3.6.5."}]}}
