{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-1334", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "apache", "product": {"product_data": [{"product_name": "spark", "version": {"version_data": [{"version_value": "2.1.2", "version_affected": "<="}, {"version_value": "2.3.0", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-200"}]}]}, "references": {"reference_data": [{"url": "https://lists.apache.org/thread.html/4d6d210e319a501b740293daaeeeadb51927111fb8261a3e4cd60060@%3Cdev.spark.apache.org%3E", "name": "[dev] 20180711 CVE-2018-1334 Apache Spark local privilege escalation vulnerability", "refsource": "MLIST", "tags": ["Mailing List", "Mitigation", "Vendor Advisory"]}, {"url": "https://spark.apache.org/security.html#CVE-2018-1334", "name": "https://spark.apache.org/security.html#CVE-2018-1334", "refsource": "CONFIRM", "tags": ["Mitigation", "Vendor Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": 'In Apache Spark 1.0.0 to 2.1.2, 2.2.0 to 2.2.1, and 2.3.0, when using PySpark or SparkR, it"s possible for a different local user to connect to the Spark application and impersonate the user running the Spark application.'}]}}
