{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-14645", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": []}}, "problemtype": {"problemtype_data": [{"description": []}]}, "references": {"reference_data": [{"url": "https://access.redhat.com/errata/RHSA-2018:2882", "name": "RHSA-2018:2882", "refsource": "REDHAT", "tags": []}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14645", "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14645", "refsource": "CONFIRM", "tags": []}, {"url": "https://usn.ubuntu.com/3780-1/", "name": "USN-3780-1", "refsource": "UBUNTU", "tags": []}, {"url": "https://www.mail-archive.com/haproxy@formilux.org/msg31253.html", "name": "[haproxy] 20180920 [ANNOUNCE] haproxy-1.8.14 - Security Update", "refsource": "MLIST", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "A flaw was discovered in the HPACK decoder of HAProxy, before 1.8.14, that is used for HTTP/2. An out-of-bounds read access in hpack_valid_idx() resulted in a remote crash and denial of service."}]}}
