{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-10855", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "redhat", "product": {"product_data": [{"product_name": "ansible_engine", "version": {"version_data": [{"version_value": "2.0", "version_affected": "="}, {"version_value": "2.4", "version_affected": "="}]}}, {"product_name": "cloudforms", "version": {"version_data": [{"version_value": "4.6", "version_affected": "="}]}}, {"product_name": "openstack", "version": {"version_data": [{"version_value": "13.0", "version_affected": "="}]}}, {"product_name": "virtualization", "version": {"version_data": [{"version_value": "4.0", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-532"}]}]}, "references": {"reference_data": [{"url": "https://access.redhat.com/errata/RHSA-2018:1948", "name": "RHSA-2018:1948", "refsource": "REDHAT", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2018:1949", "name": "RHSA-2018:1949", "refsource": "REDHAT", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2018:2022", "name": "RHSA-2018:2022", "refsource": "REDHAT", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2018:2079", "name": "RHSA-2018:2079", "refsource": "REDHAT", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2018:2184", "name": "RHSA-2018:2184", "refsource": "REDHAT", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2018:2585", "name": "RHSA-2018:2585", "refsource": "REDHAT", "tags": ["Vendor Advisory"]}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10855", "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10855", "refsource": "CONFIRM", "tags": ["Issue Tracking", "Vendor Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "Ansible 2.5 prior to 2.5.5, and 2.4 prior to 2.4.5, do not honor the no_log task flag for failed tasks. When the no_log flag has been used to protect sensitive data passed to a task from being logged, and that task does not run successfully, Ansible will expose sensitive data in log files and on the terminal of the user running Ansible."}]}}
