{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-15889", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "podofo_project", "product": {"product_data": [{"product_name": "podofo", "version": {"version_data": [{"version_value": "0.9.6", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-20"}]}]}, "references": {"reference_data": [{"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1620065", "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1620065", "refsource": "MISC", "tags": ["Exploit", "Issue Tracking", "Third Party Advisory"]}, {"url": "https://sourceforge.net/p/podofo/tickets/27/", "name": "https://sourceforge.net/p/podofo/tickets/27/", "refsource": "MISC", "tags": ["Exploit", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "In podofo 0.9.6, the function PoDoFo::PdfParser::ReadObjects() in base/PdfParser.cpp can cause the program to be aborted, because PoDoFo::PdfVecObjects::Reserve() in base/PdfVecObjects.h can be called with a large size value. Remote attackers could leverage this vulnerability to cause a denial-of-service via a crafted pdf file."}]}}
